import { type NextRequest, NextResponse } from "next/server";
import { getSheets } from "@/lib/file-utils"; // Adjust path if necessary

export async function POST(request: NextRequest) {
  try {
    // Expects a fileId (unique filename generated by the upload endpoint)
    // to identify the Excel file from which to read sheet names.
    const { fileId } = await request.json();

    if (!fileId) {
      return NextResponse.json({ error: "File identifier is required" }, { status: 400 });
    }

    // getSheets will construct the full path and read the file
    // It already handles errors like file not found
    const sheetNames = await getSheets(fileId);

    return NextResponse.json({ sheets: sheetNames });
  } catch (error) {
    console.error("Error reading sheets:", error);
    const message = error instanceof Error ? error.message : "Failed to read sheets from file";
    if (error instanceof Error && (error.message.includes("File not found") || error.message.includes("File no longer exists") || error.message.includes("No file has been uploaded"))) {
        return NextResponse.json({ error: "Uploaded file not found. Please upload again." }, { status: 404 });
    }
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
